# Generated by Django 3.1.5 on 2021-02-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 날짜'),
        ),
    ]
