# Generated by Django 3.1.6 on 2021-02-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting_role', models.CharField(max_length=50, verbose_name='캐스팅 역할')),
                ('casting_actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='casting_actor', to='kover.people')),
                ('casting_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_show', to='kover.show')),
                ('casting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_time', to='kover.time')),
            ],
        ),
    ]
