# Generated by Django 3.1.5 on 2021-02-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0002_auto_20210204_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interested_show', to='kover.show', verbose_name='관심 공연'),
        ),
    ]
