# Generated by Django 3.1.6 on 2021-02-18 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0002_casting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed_post',
            name='feed_like',
        ),
        migrations.AddField(
            model_name='feed_post',
            name='feed_like',
            field=models.ManyToManyField(blank=True, related_name='feed_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_show',
            field=models.ManyToManyField(blank=True, related_name='interested_show', to='kover.Show', verbose_name='관심 공연'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_actor',
            field=models.ManyToManyField(blank=True, related_name='like_people', to='kover.People', verbose_name='관심 배우'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_show',
            field=models.ManyToManyField(blank=True, related_name='watched_show', to='kover.Show', verbose_name='관람 공연'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_like',
        ),
        migrations.AddField(
            model_name='review',
            name='review_like',
            field=models.ManyToManyField(blank=True, related_name='review_like', to=settings.AUTH_USER_MODEL, verbose_name='리뷰 좋아요 개수'),
        ),
    ]
