# Generated by Django 3.1.6 on 2021-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0003_auto_20210219_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_post',
            name='feed_like',
            field=models.ManyToManyField(blank=True, related_name='feed_like', to='kover.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_like',
            field=models.ManyToManyField(blank=True, related_name='review_like', to='kover.Profile', verbose_name='리뷰 좋아요 개수'),
        ),
    ]
