# Generated by Django 3.1.5 on 2021-02-06 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0004_auto_20210204_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_time',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time10',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time10_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time11',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time11_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time12',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time12_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time13',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time13_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time14',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time14_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time15',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time15_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time16',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time16_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time17',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time17_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time18',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time18_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time19',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time19_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time20',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time20_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time21',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time21_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time22',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time22_5',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time23',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interested_show',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_people',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched_show',
        ),
        migrations.AddField(
            model_name='people',
            name='people_birth',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='people',
            name='people_img',
            field=models.ImageField(blank=True, upload_to='people_image/%Y/%m/%d', verbose_name='배우 사진'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_times',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show_time', to='kover.time'),
        ),
        migrations.AddField(
            model_name='time',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date_end',
            field=models.DateTimeField(null=True, verbose_name='공연 종료일'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date_start',
            field=models.DateTimeField(null=True, verbose_name='공연 시작일'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_poster',
            field=models.ImageField(blank=True, upload_to='poster_image/%Y/%m/%d', verbose_name='공연 포스터'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='유저닉네임')),
                ('grade', models.IntegerField(default=0, verbose_name='유저 등급')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 날짜')),
                ('profileimg', models.ImageField(blank=True, upload_to='profile_image/%Y/%m/%d', verbose_name='프로필 이미지')),
                ('bio', models.TextField(blank=True, verbose_name='자기 소개')),
                ('biolink', models.URLField(blank=True, verbose_name='자기 사이트')),
                ('interested_show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interested_show', to='kover.show', verbose_name='관심 공연')),
                ('like_actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='like_people', to='kover.people', verbose_name='관심 배우')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watched_show', to='kover.show', verbose_name='관람 공연')),
            ],
        ),
        migrations.AlterField(
            model_name='feed_comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='kover.profile', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='feed_post',
            name='feed_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_author', to='kover.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='kover.profile'),
        ),
    ]
