# Generated by Django 3.1.6 on 2021-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0006_auto_20210220_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_lat',
            field=models.FloatField(null=True, verbose_name='공연장 위도'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_lng',
            field=models.FloatField(null=True, verbose_name='공연장 경도'),
        ),
    ]
