# Generated by Django 3.1.5 on 2021-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0007_auto_20210206_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_lat',
            field=models.FloatField(verbose_name='공연장 위도'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_lng',
            field=models.FloatField(verbose_name='공연장 경도'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_trans',
            field=models.TextField(blank=True, verbose_name='공연장 교통편'),
        ),
    ]
