# Generated by Django 3.1.5 on 2021-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0008_auto_20210206_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_actor',
        ),
        migrations.AddField(
            model_name='show',
            name='show_actor',
            field=models.ManyToManyField(related_name='show_actor', to='kover.People'),
        ),
    ]
