# Generated by Django 3.1.5 on 2021-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0010_auto_20210206_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interested_show',
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_show',
            field=models.ManyToManyField(related_name='interested_show', to='kover.Show', verbose_name='관심 공연'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='like_actor',
        ),
        migrations.AddField(
            model_name='profile',
            name='like_actor',
            field=models.ManyToManyField(related_name='like_people', to='kover.People', verbose_name='관심 배우'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watched_show',
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_show',
            field=models.ManyToManyField(related_name='watched_show', to='kover.Show', verbose_name='관람 공연'),
        ),
    ]
