# Generated by Django 3.1.6 on 2021-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0011_auto_20210206_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_runtime',
            field=models.DurationField(verbose_name='공연 런타임'),
        ),
    ]
