# Generated by Django 3.1.6 on 2021-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kover', '0012_auto_20210207_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_runtime',
            field=models.DurationField(default='02:50:00', verbose_name='공연 런타임'),
        ),
    ]
